### ISSUE TITLE
Add your names to the authors.txt file

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-website#1]
Clone the repository and create a new branch named feature/{name-of-your-branch}. Create a PR to merge your branch into development. This is just some basic git practice to make sure everyone understands git.

**Comment by alielzei** [comment]
Link to the repo: https://github.com/Google-Developer-Student-Club-Dearborn/hd2-website

**Comment by alielzei** [comment]
Copied from ChatGPT on how to name your branch:

how to name the branch in those cases?

When creating a new branch for your pull request, it's generally a good idea to name it in a way that reflects the type of change you're making. Here are some examples of branch names that correspond to the PR types I mentioned earlier:

Bugfix: bugfix/fix-broken-login-page
Enhancement: feature/enhance-search-functionality
Refactor: refactor/improve-data-processing-algorithm
Documentation: docs/add-api-documentation
Test: test/add-unit-tests-for-payment-processing
Style: style/improve-code-formatting
Chore: chore/update-dependencies
In general, you'll want to use a prefix that corresponds to the type of change you're making (e.g., "bugfix/", "feature/", etc.), followed by a short description of the change. The description should be concise but descriptive enough to give reviewers an idea of what the branch contains.

It's also a good idea to avoid using spaces or special characters in branch names, as these can cause issues with some Git tools. Instead, you can use hyphens or underscores to separate words.
