### ISSUE TITLE
Add images of previous event in animated carousel

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-website#21]
https://foo123.github.io/examples/carousel3/

**Comment by shouryan01** [comment]
Demo looks really good! Please make a PR when ready

**Comment by sp-95** [comment]
Hey @shouryan01, I've created the [PR](https://github.com/Google-Developer-Student-Club-Dearborn/hd2-website/pull/38) for this task.
