### ISSUE TITLE
Create an "about" section

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-website#44]
For this task, we need to create an about section. It should be a pretty straightforward task. We need to show text on one side and this image
![HD2 logo](https://user-images.githubusercontent.com/32345320/236722589-a3ad76bb-a57a-4c11-866b-0164b2934740.png)

on the other. Most of your time will be spent learning how [tailwind css](https://tailwindcss.com/) works. Let me know if you have any questions!

**Comment by reganmaharjan** [comment]
I have created a pull request (#<51>) that addresses this issue. In the pull request, I have implemented the About page. Please take a look and provide your feedback.

Pull Request: https://github.com/Google-Developer-Student-Club-Dearborn/hd2-website/pull/51

Thanks!
