### ISSUE TITLE
Fix styling in the "development" branch

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-website#62]
In the development branch:

- the "back to reality" button should only show once the "disrupt reality" button has been clicked. Use the hook value to determine this.
- The "Disrupt Reality" text should be removed when in "cute" mode.
- Center the "disrupt reality" button
- hide the links at the bottom of the screen when not "disrupt reality"

**Comment by reganmaharjan** [comment]
I have submitted a pull request with some UI enhancements for this issue: [#67](https://github.com/Google-Developer-Student-Club-Dearborn/hd2-website/pull/67).
